// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(filer_cryptoFFI)
import filer_cryptoFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_filer_crypto_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_filer_crypto_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureFilerCryptoInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




public protocol VaultProtocol: AnyObject, Sendable {
    
    func decryptBlob(framed: Data) throws  -> Data
    
    func decryptBlobToFile(inPath: String, outPath: String) throws 
    
    func decryptMetadataField(field: EncryptedField) throws  -> Data
    
    func devicePublicKey()  -> [UInt8]
    
    func encryptBlob(plaintext: Data) throws  -> Data
    
    func encryptFileToBlob(inPath: String, outPath: String) throws 
    
    func encryptMetadataField(plaintext: Data) throws  -> EncryptedField
    
    func signChallenge(nonce: [UInt8])  -> DeviceSignature
    
}
open class Vault: VaultProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_filer_crypto_fn_clone_vault(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_filer_crypto_fn_free_vault(handle, $0) }
    }

    
public static func fromRecoveryPhrase(phrase: String)throws  -> Vault  {
    return try  FfiConverterTypeVault_lift(try rustCallWithError(FfiConverterTypeFilerCryptoError_lift) {
    uniffi_filer_crypto_fn_constructor_vault_from_recovery_phrase(
        FfiConverterString.lower(phrase),$0
    )
})
}
    
public static func `open`(masterSecret: [UInt8])throws  -> Vault  {
    return try  FfiConverterTypeVault_lift(try rustCallWithError(FfiConverterTypeFilerCryptoError_lift) {
    uniffi_filer_crypto_fn_constructor_vault_open(
        FfiConverterSequenceUInt8.lower(masterSecret),$0
    )
})
}
    

    
open func decryptBlob(framed: Data)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeFilerCryptoError_lift) {
    uniffi_filer_crypto_fn_method_vault_decrypt_blob(
            self.uniffiCloneHandle(),
        FfiConverterData.lower(framed),$0
    )
})
}
    
open func decryptBlobToFile(inPath: String, outPath: String)throws   {try rustCallWithError(FfiConverterTypeFilerCryptoError_lift) {
    uniffi_filer_crypto_fn_method_vault_decrypt_blob_to_file(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(inPath),
        FfiConverterString.lower(outPath),$0
    )
}
}
    
open func decryptMetadataField(field: EncryptedField)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeFilerCryptoError_lift) {
    uniffi_filer_crypto_fn_method_vault_decrypt_metadata_field(
            self.uniffiCloneHandle(),
        FfiConverterTypeEncryptedField_lower(field),$0
    )
})
}
    
open func devicePublicKey() -> [UInt8]  {
    return try!  FfiConverterSequenceUInt8.lift(try! rustCall() {
    uniffi_filer_crypto_fn_method_vault_device_public_key(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func encryptBlob(plaintext: Data)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeFilerCryptoError_lift) {
    uniffi_filer_crypto_fn_method_vault_encrypt_blob(
            self.uniffiCloneHandle(),
        FfiConverterData.lower(plaintext),$0
    )
})
}
    
open func encryptFileToBlob(inPath: String, outPath: String)throws   {try rustCallWithError(FfiConverterTypeFilerCryptoError_lift) {
    uniffi_filer_crypto_fn_method_vault_encrypt_file_to_blob(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(inPath),
        FfiConverterString.lower(outPath),$0
    )
}
}
    
open func encryptMetadataField(plaintext: Data)throws  -> EncryptedField  {
    return try  FfiConverterTypeEncryptedField_lift(try rustCallWithError(FfiConverterTypeFilerCryptoError_lift) {
    uniffi_filer_crypto_fn_method_vault_encrypt_metadata_field(
            self.uniffiCloneHandle(),
        FfiConverterData.lower(plaintext),$0
    )
})
}
    
open func signChallenge(nonce: [UInt8]) -> DeviceSignature  {
    return try!  FfiConverterTypeDeviceSignature_lift(try! rustCall() {
    uniffi_filer_crypto_fn_method_vault_sign_challenge(
            self.uniffiCloneHandle(),
        FfiConverterSequenceUInt8.lower(nonce),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeVault: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = Vault

    public static func lift(_ handle: UInt64) throws -> Vault {
        return Vault(unsafeFromHandle: handle)
    }

    public static func lower(_ value: Vault) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Vault {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: Vault, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVault_lift(_ handle: UInt64) throws -> Vault {
    return try FfiConverterTypeVault.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVault_lower(_ value: Vault) -> UInt64 {
    return FfiConverterTypeVault.lower(value)
}




public struct DeviceSignature: Equatable, Hashable {
    public var bytes: [UInt8]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(bytes: [UInt8]) {
        self.bytes = bytes
    }

    

    
}

#if compiler(>=6)
extension DeviceSignature: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDeviceSignature: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DeviceSignature {
        return
            try DeviceSignature(
                bytes: FfiConverterSequenceUInt8.read(from: &buf)
        )
    }

    public static func write(_ value: DeviceSignature, into buf: inout [UInt8]) {
        FfiConverterSequenceUInt8.write(value.bytes, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDeviceSignature_lift(_ buf: RustBuffer) throws -> DeviceSignature {
    return try FfiConverterTypeDeviceSignature.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDeviceSignature_lower(_ value: DeviceSignature) -> RustBuffer {
    return FfiConverterTypeDeviceSignature.lower(value)
}


public struct EncryptedField: Equatable, Hashable {
    public var ciphertext: Data
    public var iv: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(ciphertext: Data, iv: Data) {
        self.ciphertext = ciphertext
        self.iv = iv
    }

    

    
}

#if compiler(>=6)
extension EncryptedField: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEncryptedField: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EncryptedField {
        return
            try EncryptedField(
                ciphertext: FfiConverterData.read(from: &buf), 
                iv: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: EncryptedField, into buf: inout [UInt8]) {
        FfiConverterData.write(value.ciphertext, into: &buf)
        FfiConverterData.write(value.iv, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEncryptedField_lift(_ buf: RustBuffer) throws -> EncryptedField {
    return try FfiConverterTypeEncryptedField.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEncryptedField_lower(_ value: EncryptedField) -> RustBuffer {
    return FfiConverterTypeEncryptedField.lower(value)
}


public enum FilerCryptoError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case Aead(message: String)
    
    case InvalidPhrase(message: String)
    
    case InvalidKeyLength(message: String)
    
    case InvalidSignature(message: String)
    
    case Randomness(message: String)
    
    case Io(message: String)
    

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension FilerCryptoError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFilerCryptoError: FfiConverterRustBuffer {
    typealias SwiftType = FilerCryptoError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FilerCryptoError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Aead(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .InvalidPhrase(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .InvalidKeyLength(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 4: return .InvalidSignature(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 5: return .Randomness(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 6: return .Io(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FilerCryptoError, into buf: inout [UInt8]) {
        switch value {

        

        
        case .Aead(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))
        case .InvalidPhrase(_ /* message is ignored*/):
            writeInt(&buf, Int32(2))
        case .InvalidKeyLength(_ /* message is ignored*/):
            writeInt(&buf, Int32(3))
        case .InvalidSignature(_ /* message is ignored*/):
            writeInt(&buf, Int32(4))
        case .Randomness(_ /* message is ignored*/):
            writeInt(&buf, Int32(5))
        case .Io(_ /* message is ignored*/):
            writeInt(&buf, Int32(6))

        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFilerCryptoError_lift(_ buf: RustBuffer) throws -> FilerCryptoError {
    return try FfiConverterTypeFilerCryptoError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFilerCryptoError_lower(_ value: FilerCryptoError) -> RustBuffer {
    return FfiConverterTypeFilerCryptoError.lower(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceUInt8: FfiConverterRustBuffer {
    typealias SwiftType = [UInt8]

    public static func write(_ value: [UInt8], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterUInt8.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [UInt8] {
        let len: Int32 = try readInt(&buf)
        var seq = [UInt8]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterUInt8.read(from: &buf))
        }
        return seq
    }
}
public func generateMasterSecret()throws  -> [UInt8]  {
    return try  FfiConverterSequenceUInt8.lift(try rustCallWithError(FfiConverterTypeFilerCryptoError_lift) {
    uniffi_filer_crypto_fn_func_generate_master_secret($0
    )
})
}
public func phraseToSecret(phrase: String)throws  -> [UInt8]  {
    return try  FfiConverterSequenceUInt8.lift(try rustCallWithError(FfiConverterTypeFilerCryptoError_lift) {
    uniffi_filer_crypto_fn_func_phrase_to_secret(
        FfiConverterString.lower(phrase),$0
    )
})
}
public func secretToPhrase(secret: [UInt8])throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeFilerCryptoError_lift) {
    uniffi_filer_crypto_fn_func_secret_to_phrase(
        FfiConverterSequenceUInt8.lower(secret),$0
    )
})
}
public func verifySignature(publicKey: [UInt8], nonce: [UInt8], signature: [UInt8])throws   {try rustCallWithError(FfiConverterTypeFilerCryptoError_lift) {
    uniffi_filer_crypto_fn_func_verify_signature(
        FfiConverterSequenceUInt8.lower(publicKey),
        FfiConverterSequenceUInt8.lower(nonce),
        FfiConverterSequenceUInt8.lower(signature),$0
    )
}
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_filer_crypto_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_filer_crypto_checksum_func_generate_master_secret() != 48501) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_filer_crypto_checksum_func_phrase_to_secret() != 52504) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_filer_crypto_checksum_func_secret_to_phrase() != 61979) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_filer_crypto_checksum_func_verify_signature() != 24370) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_filer_crypto_checksum_method_vault_decrypt_blob() != 32882) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_filer_crypto_checksum_method_vault_decrypt_blob_to_file() != 27662) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_filer_crypto_checksum_method_vault_decrypt_metadata_field() != 35262) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_filer_crypto_checksum_method_vault_device_public_key() != 43615) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_filer_crypto_checksum_method_vault_encrypt_blob() != 44355) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_filer_crypto_checksum_method_vault_encrypt_file_to_blob() != 8057) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_filer_crypto_checksum_method_vault_encrypt_metadata_field() != 12280) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_filer_crypto_checksum_method_vault_sign_challenge() != 6062) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_filer_crypto_checksum_constructor_vault_from_recovery_phrase() != 40323) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_filer_crypto_checksum_constructor_vault_open() != 14736) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureFilerCryptoInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all