// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V4
    #ifndef UNIFFI_SHARED_HEADER_V4
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V4
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V4
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️

typedef struct RustBuffer
{
    uint64_t capacity;
    uint64_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H
#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t, int8_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK
typedef void (*UniffiForeignFutureDroppedCallback)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_CLONE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_CLONE
typedef uint64_t (*UniffiCallbackInterfaceClone)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK_STRUCT
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK_STRUCT
typedef struct UniffiForeignFutureDroppedCallbackStruct {
    uint64_t handle;
    UniffiForeignFutureDroppedCallback _Nonnull free;
} UniffiForeignFutureDroppedCallbackStruct;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U8
typedef struct UniffiForeignFutureResultU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t, UniffiForeignFutureResultU8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I8
typedef struct UniffiForeignFutureResultI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t, UniffiForeignFutureResultI8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U16
typedef struct UniffiForeignFutureResultU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t, UniffiForeignFutureResultU16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I16
typedef struct UniffiForeignFutureResultI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t, UniffiForeignFutureResultI16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U32
typedef struct UniffiForeignFutureResultU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t, UniffiForeignFutureResultU32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I32
typedef struct UniffiForeignFutureResultI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t, UniffiForeignFutureResultI32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U64
typedef struct UniffiForeignFutureResultU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t, UniffiForeignFutureResultU64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I64
typedef struct UniffiForeignFutureResultI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t, UniffiForeignFutureResultI64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F32
typedef struct UniffiForeignFutureResultF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t, UniffiForeignFutureResultF32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F64
typedef struct UniffiForeignFutureResultF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t, UniffiForeignFutureResultF64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_RUST_BUFFER
typedef struct UniffiForeignFutureResultRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t, UniffiForeignFutureResultRustBuffer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_VOID
typedef struct UniffiForeignFutureResultVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureResultVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t, UniffiForeignFutureResultVoid
    );

#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FILER_CRYPTO_FN_CLONE_VAULT
#define UNIFFI_FFIDEF_UNIFFI_FILER_CRYPTO_FN_CLONE_VAULT
uint64_t uniffi_filer_crypto_fn_clone_vault(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FILER_CRYPTO_FN_FREE_VAULT
#define UNIFFI_FFIDEF_UNIFFI_FILER_CRYPTO_FN_FREE_VAULT
void uniffi_filer_crypto_fn_free_vault(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FILER_CRYPTO_FN_CONSTRUCTOR_VAULT_FROM_RECOVERY_PHRASE
#define UNIFFI_FFIDEF_UNIFFI_FILER_CRYPTO_FN_CONSTRUCTOR_VAULT_FROM_RECOVERY_PHRASE
uint64_t uniffi_filer_crypto_fn_constructor_vault_from_recovery_phrase(RustBuffer phrase, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FILER_CRYPTO_FN_CONSTRUCTOR_VAULT_OPEN
#define UNIFFI_FFIDEF_UNIFFI_FILER_CRYPTO_FN_CONSTRUCTOR_VAULT_OPEN
uint64_t uniffi_filer_crypto_fn_constructor_vault_open(RustBuffer master_secret, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FILER_CRYPTO_FN_METHOD_VAULT_DECRYPT_BLOB
#define UNIFFI_FFIDEF_UNIFFI_FILER_CRYPTO_FN_METHOD_VAULT_DECRYPT_BLOB
RustBuffer uniffi_filer_crypto_fn_method_vault_decrypt_blob(uint64_t ptr, RustBuffer framed, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FILER_CRYPTO_FN_METHOD_VAULT_DECRYPT_BLOB_TO_FILE
#define UNIFFI_FFIDEF_UNIFFI_FILER_CRYPTO_FN_METHOD_VAULT_DECRYPT_BLOB_TO_FILE
void uniffi_filer_crypto_fn_method_vault_decrypt_blob_to_file(uint64_t ptr, RustBuffer in_path, RustBuffer out_path, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FILER_CRYPTO_FN_METHOD_VAULT_DECRYPT_METADATA_FIELD
#define UNIFFI_FFIDEF_UNIFFI_FILER_CRYPTO_FN_METHOD_VAULT_DECRYPT_METADATA_FIELD
RustBuffer uniffi_filer_crypto_fn_method_vault_decrypt_metadata_field(uint64_t ptr, RustBuffer field, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FILER_CRYPTO_FN_METHOD_VAULT_DEVICE_PUBLIC_KEY
#define UNIFFI_FFIDEF_UNIFFI_FILER_CRYPTO_FN_METHOD_VAULT_DEVICE_PUBLIC_KEY
RustBuffer uniffi_filer_crypto_fn_method_vault_device_public_key(uint64_t ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FILER_CRYPTO_FN_METHOD_VAULT_ENCRYPT_BLOB
#define UNIFFI_FFIDEF_UNIFFI_FILER_CRYPTO_FN_METHOD_VAULT_ENCRYPT_BLOB
RustBuffer uniffi_filer_crypto_fn_method_vault_encrypt_blob(uint64_t ptr, RustBuffer plaintext, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FILER_CRYPTO_FN_METHOD_VAULT_ENCRYPT_FILE_TO_BLOB
#define UNIFFI_FFIDEF_UNIFFI_FILER_CRYPTO_FN_METHOD_VAULT_ENCRYPT_FILE_TO_BLOB
void uniffi_filer_crypto_fn_method_vault_encrypt_file_to_blob(uint64_t ptr, RustBuffer in_path, RustBuffer out_path, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FILER_CRYPTO_FN_METHOD_VAULT_ENCRYPT_METADATA_FIELD
#define UNIFFI_FFIDEF_UNIFFI_FILER_CRYPTO_FN_METHOD_VAULT_ENCRYPT_METADATA_FIELD
RustBuffer uniffi_filer_crypto_fn_method_vault_encrypt_metadata_field(uint64_t ptr, RustBuffer plaintext, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FILER_CRYPTO_FN_METHOD_VAULT_SIGN_CHALLENGE
#define UNIFFI_FFIDEF_UNIFFI_FILER_CRYPTO_FN_METHOD_VAULT_SIGN_CHALLENGE
RustBuffer uniffi_filer_crypto_fn_method_vault_sign_challenge(uint64_t ptr, RustBuffer nonce, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FILER_CRYPTO_FN_FUNC_GENERATE_MASTER_SECRET
#define UNIFFI_FFIDEF_UNIFFI_FILER_CRYPTO_FN_FUNC_GENERATE_MASTER_SECRET
RustBuffer uniffi_filer_crypto_fn_func_generate_master_secret(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FILER_CRYPTO_FN_FUNC_PHRASE_TO_SECRET
#define UNIFFI_FFIDEF_UNIFFI_FILER_CRYPTO_FN_FUNC_PHRASE_TO_SECRET
RustBuffer uniffi_filer_crypto_fn_func_phrase_to_secret(RustBuffer phrase, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FILER_CRYPTO_FN_FUNC_SECRET_TO_PHRASE
#define UNIFFI_FFIDEF_UNIFFI_FILER_CRYPTO_FN_FUNC_SECRET_TO_PHRASE
RustBuffer uniffi_filer_crypto_fn_func_secret_to_phrase(RustBuffer secret, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FILER_CRYPTO_FN_FUNC_VERIFY_SIGNATURE
#define UNIFFI_FFIDEF_UNIFFI_FILER_CRYPTO_FN_FUNC_VERIFY_SIGNATURE
void uniffi_filer_crypto_fn_func_verify_signature(RustBuffer public_key, RustBuffer nonce, RustBuffer signature, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUSTBUFFER_ALLOC
RustBuffer ffi_filer_crypto_rustbuffer_alloc(uint64_t size, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_filer_crypto_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUSTBUFFER_FREE
void ffi_filer_crypto_rustbuffer_free(RustBuffer buf, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUSTBUFFER_RESERVE
RustBuffer ffi_filer_crypto_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_POLL_U8
void ffi_filer_crypto_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_CANCEL_U8
void ffi_filer_crypto_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_FREE_U8
void ffi_filer_crypto_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_filer_crypto_rust_future_complete_u8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_POLL_I8
void ffi_filer_crypto_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_CANCEL_I8
void ffi_filer_crypto_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_FREE_I8
void ffi_filer_crypto_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_COMPLETE_I8
int8_t ffi_filer_crypto_rust_future_complete_i8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_POLL_U16
void ffi_filer_crypto_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_CANCEL_U16
void ffi_filer_crypto_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_FREE_U16
void ffi_filer_crypto_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_filer_crypto_rust_future_complete_u16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_POLL_I16
void ffi_filer_crypto_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_CANCEL_I16
void ffi_filer_crypto_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_FREE_I16
void ffi_filer_crypto_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_COMPLETE_I16
int16_t ffi_filer_crypto_rust_future_complete_i16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_POLL_U32
void ffi_filer_crypto_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_CANCEL_U32
void ffi_filer_crypto_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_FREE_U32
void ffi_filer_crypto_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_filer_crypto_rust_future_complete_u32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_POLL_I32
void ffi_filer_crypto_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_CANCEL_I32
void ffi_filer_crypto_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_FREE_I32
void ffi_filer_crypto_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_COMPLETE_I32
int32_t ffi_filer_crypto_rust_future_complete_i32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_POLL_U64
void ffi_filer_crypto_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_CANCEL_U64
void ffi_filer_crypto_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_FREE_U64
void ffi_filer_crypto_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_filer_crypto_rust_future_complete_u64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_POLL_I64
void ffi_filer_crypto_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_CANCEL_I64
void ffi_filer_crypto_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_FREE_I64
void ffi_filer_crypto_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_COMPLETE_I64
int64_t ffi_filer_crypto_rust_future_complete_i64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_POLL_F32
void ffi_filer_crypto_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_CANCEL_F32
void ffi_filer_crypto_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_FREE_F32
void ffi_filer_crypto_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_COMPLETE_F32
float ffi_filer_crypto_rust_future_complete_f32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_POLL_F64
void ffi_filer_crypto_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_CANCEL_F64
void ffi_filer_crypto_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_FREE_F64
void ffi_filer_crypto_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_COMPLETE_F64
double ffi_filer_crypto_rust_future_complete_f64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_filer_crypto_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_filer_crypto_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_filer_crypto_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_filer_crypto_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_POLL_VOID
void ffi_filer_crypto_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_CANCEL_VOID
void ffi_filer_crypto_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_FREE_VOID
void ffi_filer_crypto_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_FILER_CRYPTO_RUST_FUTURE_COMPLETE_VOID
void ffi_filer_crypto_rust_future_complete_void(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FILER_CRYPTO_CHECKSUM_FUNC_GENERATE_MASTER_SECRET
#define UNIFFI_FFIDEF_UNIFFI_FILER_CRYPTO_CHECKSUM_FUNC_GENERATE_MASTER_SECRET
uint16_t uniffi_filer_crypto_checksum_func_generate_master_secret(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FILER_CRYPTO_CHECKSUM_FUNC_PHRASE_TO_SECRET
#define UNIFFI_FFIDEF_UNIFFI_FILER_CRYPTO_CHECKSUM_FUNC_PHRASE_TO_SECRET
uint16_t uniffi_filer_crypto_checksum_func_phrase_to_secret(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FILER_CRYPTO_CHECKSUM_FUNC_SECRET_TO_PHRASE
#define UNIFFI_FFIDEF_UNIFFI_FILER_CRYPTO_CHECKSUM_FUNC_SECRET_TO_PHRASE
uint16_t uniffi_filer_crypto_checksum_func_secret_to_phrase(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FILER_CRYPTO_CHECKSUM_FUNC_VERIFY_SIGNATURE
#define UNIFFI_FFIDEF_UNIFFI_FILER_CRYPTO_CHECKSUM_FUNC_VERIFY_SIGNATURE
uint16_t uniffi_filer_crypto_checksum_func_verify_signature(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FILER_CRYPTO_CHECKSUM_METHOD_VAULT_DECRYPT_BLOB
#define UNIFFI_FFIDEF_UNIFFI_FILER_CRYPTO_CHECKSUM_METHOD_VAULT_DECRYPT_BLOB
uint16_t uniffi_filer_crypto_checksum_method_vault_decrypt_blob(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FILER_CRYPTO_CHECKSUM_METHOD_VAULT_DECRYPT_BLOB_TO_FILE
#define UNIFFI_FFIDEF_UNIFFI_FILER_CRYPTO_CHECKSUM_METHOD_VAULT_DECRYPT_BLOB_TO_FILE
uint16_t uniffi_filer_crypto_checksum_method_vault_decrypt_blob_to_file(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FILER_CRYPTO_CHECKSUM_METHOD_VAULT_DECRYPT_METADATA_FIELD
#define UNIFFI_FFIDEF_UNIFFI_FILER_CRYPTO_CHECKSUM_METHOD_VAULT_DECRYPT_METADATA_FIELD
uint16_t uniffi_filer_crypto_checksum_method_vault_decrypt_metadata_field(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FILER_CRYPTO_CHECKSUM_METHOD_VAULT_DEVICE_PUBLIC_KEY
#define UNIFFI_FFIDEF_UNIFFI_FILER_CRYPTO_CHECKSUM_METHOD_VAULT_DEVICE_PUBLIC_KEY
uint16_t uniffi_filer_crypto_checksum_method_vault_device_public_key(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FILER_CRYPTO_CHECKSUM_METHOD_VAULT_ENCRYPT_BLOB
#define UNIFFI_FFIDEF_UNIFFI_FILER_CRYPTO_CHECKSUM_METHOD_VAULT_ENCRYPT_BLOB
uint16_t uniffi_filer_crypto_checksum_method_vault_encrypt_blob(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FILER_CRYPTO_CHECKSUM_METHOD_VAULT_ENCRYPT_FILE_TO_BLOB
#define UNIFFI_FFIDEF_UNIFFI_FILER_CRYPTO_CHECKSUM_METHOD_VAULT_ENCRYPT_FILE_TO_BLOB
uint16_t uniffi_filer_crypto_checksum_method_vault_encrypt_file_to_blob(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FILER_CRYPTO_CHECKSUM_METHOD_VAULT_ENCRYPT_METADATA_FIELD
#define UNIFFI_FFIDEF_UNIFFI_FILER_CRYPTO_CHECKSUM_METHOD_VAULT_ENCRYPT_METADATA_FIELD
uint16_t uniffi_filer_crypto_checksum_method_vault_encrypt_metadata_field(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FILER_CRYPTO_CHECKSUM_METHOD_VAULT_SIGN_CHALLENGE
#define UNIFFI_FFIDEF_UNIFFI_FILER_CRYPTO_CHECKSUM_METHOD_VAULT_SIGN_CHALLENGE
uint16_t uniffi_filer_crypto_checksum_method_vault_sign_challenge(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FILER_CRYPTO_CHECKSUM_CONSTRUCTOR_VAULT_FROM_RECOVERY_PHRASE
#define UNIFFI_FFIDEF_UNIFFI_FILER_CRYPTO_CHECKSUM_CONSTRUCTOR_VAULT_FROM_RECOVERY_PHRASE
uint16_t uniffi_filer_crypto_checksum_constructor_vault_from_recovery_phrase(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FILER_CRYPTO_CHECKSUM_CONSTRUCTOR_VAULT_OPEN
#define UNIFFI_FFIDEF_UNIFFI_FILER_CRYPTO_CHECKSUM_CONSTRUCTOR_VAULT_OPEN
uint16_t uniffi_filer_crypto_checksum_constructor_vault_open(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FILER_CRYPTO_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_FILER_CRYPTO_UNIFFI_CONTRACT_VERSION
uint32_t ffi_filer_crypto_uniffi_contract_version(void
    
);
#endif

